name: Gatsby Preview Publish

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: 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
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
